### ISSUE TITLE
Make a question categorical instead of text

### ISSUE THREAD

**Issue by akuffoamankwah1** [radyakin/time_use_quest#1]
Need to change "Until when" question to single select with options from 04:15 - 04:00 am.

**Comment by radyakin** [comment]
1. You will not be able to record activities precisely. For example, if commute takes precisely 50 minutes the respondent will need to change that to 45 minutes or 60 minutes.
2. The questionnaire currently allows parametrization that allows the day to start from any hour. By imposing categories this possibility is forfeited.

**Comment by akuffoamankwah1** [comment]
Agree to both 1 and 2

**Comment by akuffoamankwah1** [comment]
[Codes.xlsx](https://github.com/radyakin/time_use_quest/files/15474888/Codes.xlsx)

**Comment by akuffoamankwah1** [comment]
Need to build a filter into the "Until when" question such that options for @rowcode > @rowcode-1
